backend:
  name: github
  repo: svoltastudenti/atupertu
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"
collections:
  - name: "associations" # Used in routes, e.g., /admin/collections/blog
    label: "Associazioni" # Used in the UI
    folder: "_posts/associations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "associations"}
      - {label: "Categoria", name: "category", widget: "hidden", default: "associations"}
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "SKU", name: "sku", widget: "string"}
      - {label: "Descrizione", name: "body", widget: "markdown"}
      - {label: "Cover", name: "cover", widget: "image", required: true}
      - {label: "Pubblicato", name: "published", widget: "hidden", default: true}
      - {label: "Data di Pubblicazione (la programmazione NON e' supportata)", name: "date", widget: "datetime"}
